"""
app.py — Foresight: Hindsight-Powered Deal Intelligence

Unified Streamlit entry point for the full Foresight demo.

Layout (top → bottom):
  [Member 1] Deal Overview Header (ACME deal context + stakeholder chips)
  [Member 1] Pre-Call Executive Brief Card (Groq LLM, grounded in Hindsight memory)
  [Member 2] Collision Check Engine + Dynamic Memory Reflection (Tanmaya)

Run with:
    streamlit run app.py
"""

import os
import sys
import json
import streamlit as st

# Ensure the project root is always on sys.path (important when launched from sub-dirs)
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from memory import DealMemoryBank

# Member 2 (Tanmaya) components
from tanmaya.collision_detector import TanmayaCollisionDetector
from tanmaya.collision_ui import render_collision_cards, render_actionable_guidance

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Foresight — Deal Intelligence",
    page_icon="🔮",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ---------------------------------------------------------------------------
# Session state initialisation
# ---------------------------------------------------------------------------
if "deal_memory" not in st.session_state:
    st.session_state.deal_memory = DealMemoryBank()

if "memory_seeded" not in st.session_state:
    st.session_state.memory_seeded = False

if "pre_call_brief" not in st.session_state:
    st.session_state.pre_call_brief = None

if "brief_error" not in st.session_state:
    st.session_state.brief_error = None

if "memory_updated_event" not in st.session_state:
    st.session_state.memory_updated_event = False

memory: DealMemoryBank = st.session_state.deal_memory

# Load Tanmaya's company KB (her copy has the keys her detector expects)
_tanmaya_kb_path = os.path.join(os.path.dirname(__file__), "tanmaya", "company_kb.json")
with open(_tanmaya_kb_path, "r", encoding="utf-8") as _f:
    _tanmaya_kb = json.load(_f)

detector = TanmayaCollisionDetector(company_kb=_tanmaya_kb)

# ---------------------------------------------------------------------------
# ── SECTION 1 (Member 1): DEAL OVERVIEW HEADER
# ---------------------------------------------------------------------------
st.markdown("# 🔮 Foresight — Hindsight-Powered Deal Intelligence")
st.caption("*Powered by Hindsight memory · Groq LLaMA-3.3-70b · Veridian × ACME Corp*")
st.divider()

md = memory.metadata

# Top KPI strip
kpi1, kpi2, kpi3, kpi4, kpi5 = st.columns(5)
kpi1.metric("Customer", md.get("customer_name", "ACME Corp"))
kpi2.metric("Stage", "Proposal Review")
kpi3.metric("Deal Value (ARR)", f"${md.get('initial_quote_arr', 72000):,}")
kpi4.metric("Interactions Indexed", md.get("total_interactions", 9))
kpi5.metric("Status", "🔴 High Stakes")

st.markdown("---")

# Stakeholder chips row
st.markdown("#### 👥 Deal Stakeholders")

SENTIMENT_COLOURS = {
    "Strongly Positive": "#1a7340",
    "Positive with Technical Rigor": "#2e6da4",
    "Budget-Conscious / Skeptical of Lock-in": "#b85c00",
    "Strict / Non-negotiable": "#9b1c1c",
    "Aggressive / Procurement Tactics": "#5a3e8e",
}

ROLE_ICONS = {
    "Internal Champion": "🏆",
    "Technical Evaluator": "🔧",
    "Economic Buyer": "💰",
    "Security Gatekeeper": "🔒",
    "Commercial Negotiator": "📋",
}

chip_cols = st.columns(len(memory.stakeholders))
for col, s in zip(chip_cols, memory.stakeholders):
    icon = ROLE_ICONS.get(s.get("role", ""), "👤")
    colour = SENTIMENT_COLOURS.get(s.get("sentiment", ""), "#444")
    col.markdown(
        f"""<div style="
                border-left: 4px solid {colour};
                padding: 8px 10px;
                border-radius: 6px;
                background: #1e1e2e;
                font-size: 0.85rem;
                line-height: 1.5;
            ">
            <strong>{icon} {s['name']}</strong><br>
            <span style="color:#aaa;">{s['title']}</span><br>
            <span style="color:#ccc;font-size:0.78rem;">{s['role']}</span>
        </div>""",
        unsafe_allow_html=True,
    )

st.markdown("---")

# ---------------------------------------------------------------------------
# ── SECTION 2 (Member 1): PRE-CALL EXECUTIVE BRIEF
# ---------------------------------------------------------------------------
st.markdown("## 📋 Pre-Call Executive Brief")
st.caption(
    "10-second dossier generated by Foresight — grounded exclusively in Hindsight deal memory."
)

m1_col1, m1_col2 = st.columns([2, 1])

with m1_col2:
    seed_btn = st.button(
        "🌱 Seed Deal Memory",
        use_container_width=True,
        help="Indexes all 9 ACME interactions, stakeholder sensitivities, and commitments into Hindsight.",
    )
    brief_btn = st.button(
        "⚡ Generate Pre-Call Brief",
        type="primary",
        use_container_width=True,
        help="Queries deal memory and uses Groq LLaMA-3.3-70b to generate the brief.",
    )

    if st.session_state.memory_seeded:
        st.success("✅ Memory Seeded", icon="✅")
    else:
        st.info("Memory not yet seeded this session.", icon="ℹ️")

with m1_col1:
    if seed_btn:
        with st.spinner("Seeding deal memory from Hindsight bank…"):
            result = memory.seed_deal_memory()
            st.session_state.memory_seeded = True
        st.success(
            f"✅ Seeded {result['total_retained']} memory entries: "
            f"{result['seeded_interactions']} interactions · "
            f"{result['seeded_stakeholders']} stakeholder profiles · "
            f"{result['seeded_commitments']} commitments"
        )

    if brief_btn:
        with st.spinner("Querying Hindsight memory & generating brief with Groq…"):
            try:
                brief = memory.generate_pre_call_brief()
                st.session_state.pre_call_brief = brief
                st.session_state.brief_error = None
            except RuntimeError as e:
                st.session_state.brief_error = str(e)
                st.session_state.pre_call_brief = None

# Render the brief if available
brief = st.session_state.pre_call_brief
err = st.session_state.brief_error

if err:
    st.error(f"**Could not generate brief:** {err}")

elif brief:
    # Schema warning banner (only shown if LLM drifted from schema)
    if brief.get("_schema_warning"):
        st.warning(f"⚠️ {brief['_schema_warning']}")

    # Headline
    st.info(f"**Situation:** {brief.get('headline', 'N/A')}")

    # Coaching tip — the single most important thing
    coaching = brief.get("one_sentence_coaching_tip", "")
    if coaching:
        st.markdown(
            f"""<div style="
                background:#2d1b00;border-left:4px solid #f5a623;
                padding:10px 14px;border-radius:6px;margin-bottom:12px;">
                🎯 <strong>Coach's Tip:</strong> {coaching}
            </div>""",
            unsafe_allow_html=True,
        )

    brief_tab1, brief_tab2, brief_tab3, brief_tab4 = st.tabs(
        ["👥 Stakeholder Dossier", "🏁 Competitor Intel", "⚠️ Commitments at Risk", "💡 Winning Tactics"]
    )

    # --- Tab 1: Stakeholder Sensitivities ---
    with brief_tab1:
        sensitivities = brief.get("stakeholder_sensitivities", [])
        if not sensitivities:
            st.write("No stakeholder data in brief.")
        for s in sensitivities:
            name = s.get("name", "Unknown")
            role = s.get("role", "")
            sensitivity = s.get("sensitivity", "")
            approach = s.get("recommended_approach", "")
            icon = ROLE_ICONS.get(role, "👤")
            colour = next(
                (SENTIMENT_COLOURS[k] for k in SENTIMENT_COLOURS if k.lower() in role.lower()),
                "#666",
            )
            with st.expander(f"{icon} **{name}** — {role}", expanded=True):
                st.markdown(f"**🧠 Core Sensitivity:** {sensitivity}")
                st.markdown(
                    f"""<div style="
                        background:#0d2137;border-left:3px solid #2e6da4;
                        padding:8px 12px;border-radius:5px;margin-top:6px;">
                        💬 <strong>Recommended Approach:</strong> {approach}
                    </div>""",
                    unsafe_allow_html=True,
                )

    # --- Tab 2: Competitor Intel ---
    with brief_tab2:
        ci = brief.get("competitor_intelligence", {})
        if not ci:
            st.write("No competitor data in brief.")
        else:
            comp_cols = st.columns(2)
            with comp_cols[0]:
                st.markdown(f"**Competitor:** `{ci.get('competitor', 'N/A')}`")
                st.markdown(f"**Their Offer:** {ci.get('their_offer', 'N/A')}")
                st.markdown(f"**Battle Card Tip:** {ci.get('battle_card_tip', 'N/A')}")
            with comp_cols[1]:
                st.markdown("**Our Differentiators:**")
                for d in ci.get("our_differentiators", []):
                    st.markdown(f"- {d}")

    # --- Tab 3: Open Commitments at Risk ---
    with brief_tab3:
        at_risk = brief.get("open_commitments_at_risk", [])
        if not at_risk:
            st.success("All commitments are fulfilled — no open risks.")
        for c in at_risk:
            status = c.get("status", "")
            badge_colour = "🔴" if "overdue" in status.lower() else "🟡"
            with st.expander(
                f"{badge_colour} **{c.get('commitment', 'N/A')}** → {c.get('recipient', 'N/A')} [{status}]"
            ):
                st.markdown(f"**Risk if unaddressed:** {c.get('risk', 'N/A')}")

    # --- Tab 4: Winning Tactics ---
    with brief_tab4:
        tactics = brief.get("winning_tactics", [])
        if not tactics:
            st.write("No tactics generated.")
        for i, tactic in enumerate(tactics, 1):
            st.markdown(
                f"""<div style="
                    background:#0d1f0d;border-left:3px solid #2da44e;
                    padding:8px 12px;border-radius:5px;margin-bottom:8px;">
                    <strong>#{i}</strong> {tactic}
                </div>""",
                unsafe_allow_html=True,
            )

else:
    # Placeholder card before brief is generated
    st.markdown(
        """<div style="
            border:1px dashed #555;border-radius:8px;padding:24px;
            text-align:center;color:#888;background:#111;">
            <h3 style="color:#888;">⚡ Pre-Call Brief Not Yet Generated</h3>
            <p>Click <strong>[ ⚡ Generate Pre-Call Brief ]</strong> to produce an evidence-based
            10-second dossier from Hindsight deal memory.</p>
            <p style="font-size:0.8rem;">Optionally, click <strong>[ 🌱 Seed Deal Memory ]</strong>
            first to push all interactions into the Hindsight Cloud bank.</p>
        </div>""",
        unsafe_allow_html=True,
    )

st.markdown("---")

# ---------------------------------------------------------------------------
# ── SECTION 3 (Member 2 — Tanmaya): COLLISION CHECK ENGINE
# ---------------------------------------------------------------------------
st.markdown("## ⚡ Collision Check & Dynamic Memory Reflection")
st.caption("Built by **Tanmaya (Member 2)** — Collision Engine & Dynamic Reflection Lead")

# SOC-2 state (shared memory object — same instance Tanmaya's app uses)
soc2_comm = next((c for c in memory.commitments if c["id"] == "COMM-02"), None)
is_soc2_sent = soc2_comm and soc2_comm.get("status") == "Completed"

req_col, btn_col = st.columns([3, 1])

with req_col:
    default_prompt = "Can you give us 40% off and get us live into production in two weeks?"
    user_request = st.text_area(
        "Incoming Customer Negotiation Request:",
        value=default_prompt,
        height=85,
        key="collision_input",
    )

with btn_col:
    st.markdown("<br>", unsafe_allow_html=True)
    check_btn = st.button(
        "🔍 Run Collision Check", type="primary", use_container_width=True, key="run_collision"
    )

    if not is_soc2_sent:
        mark_btn = st.button(
            "🚀 Mark SOC-2 Sent to Nadia",
            use_container_width=True,
            key="mark_soc2",
            help="Simulate delivering the promised SOC-2 report — watch the collision cards update live.",
        )
        if mark_btn:
            memory.mark_soc2_sent()
            st.session_state.memory_updated_event = True
            # Also refresh the pre-call brief automatically if one exists
            if st.session_state.pre_call_brief:
                st.session_state.pre_call_brief = None  # signal to regenerate
            st.rerun()
    else:
        st.button("✅ SOC-2 Delivered", disabled=True, use_container_width=True)
        reset_btn = st.button(
            "🔄 Reset Demo",
            use_container_width=True,
            key="reset_demo",
            help="Reset memory to Overdue state to replay the demo.",
        )
        if reset_btn:
            st.session_state.deal_memory = DealMemoryBank()
            st.session_state.memory_updated_event = False
            st.session_state.memory_seeded = False
            st.session_state.pre_call_brief = None
            st.rerun()

# Dynamic memory reaction banner
if is_soc2_sent:
    st.success(
        "🎉 **DYNAMIC MEMORY REACTION TRIGGERED!** "
        "SOC-2 Report marked Delivered to Nadia Chen. "
        "Collision Engine re-evaluated: 🔴 Security Blocker → ✅ Cleared. "
        "Strategic guidance shifted to offensive $49k closing plan."
    )

# Run collision check and render Tanmaya's components
context = memory.get_all_context()
results = detector.check_collisions(customer_request=user_request, deal_context=context)

render_collision_cards(results)
st.markdown("---")
render_actionable_guidance(results)

# ---------------------------------------------------------------------------
# Sidebar — audit log (debug helper during demo)
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("### 🗃️ Hindsight Audit Log")
    st.caption("Last 10 retain() calls this session")
    log = memory.memory_audit_log[-10:]
    if not log:
        st.write("No events yet.")
    for entry in reversed(log):
        st.markdown(
            f"**{entry['category']}** `{entry['timestamp'][:19]}`\n\n"
            f"{entry['content'][:120]}…"
        )
        st.divider()
